CREATE TABLE model (
	id INTEGER AUTO_INCREMENT NOT NULL,
	uuid CHAR(36) NOT NULL,
	name VARCHAR(100) NOT NULL,
	created DATETIME NOT NULL,
	updated DATETIME NOT NULL,
	author VARCHAR(100) NOT NULL,
	CONSTRAINT pk_model PRIMARY KEY (id),
	CONSTRAINT uq_model_uuid UNIQUE (uuid)
);
